name: Track GitHub Traffic

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch GitHub traffic and log
      run: |
        python .github/scripts/fetch_traffic.py

    - name: Commit traffic log
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add traffic-log.csv
        git commit -m "Update traffic stats" || echo "No changes"
        git push
